; ESP8266 NodeMCU + GC9A01 240x240 round display
[env:nodemcu]
platform = espressif8266
board = nodemcu
framework = arduino
monitor_speed = 115200
build_unflags =
    -std=gnu++11
build_flags =
    -std=gnu++17
    -Wall
lib_deps =
    lovyan03/LovyanGFX
    tzapu/WiFiManager
    bblanchon/ArduinoJson
